---

metaedit-main:
  path: /
  defaults: {
    _controller: 'SimpleSAML\Module\metaedit\Controller\MetaEditor::main'
  }

metaedit-edit:
  path: /edit
  defaults: {
    _controller: 'SimpleSAML\Module\metaedit\Controller\MetaEditor::edit'
  }

metaedit-import:
  path: /import
  defaults: {
    _controller: 'SimpleSAML\Module\metaedit\Controller\MetaEditor::import'
  }
